nodeLinker: node-modules
logFilters:
  - code: YN0013
    level: discard
packageExtensions: 
    ibm_db@*: 
      dependencies: 
        node-gyp: "^10.0.1"
  
yarnPath: .yarn/releases/yarn-3.4.1.cjs
