name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -f Dockerfile.rocketadmin-agent -t rocketadmin-agent .
          docker tag rocketadmin-agent:latest ghcr.io/rocketadmin/rocketadmin-agent:latest
          docker push ghcr.io/rocketadmin/rocketadmin-agent:latest